# Production Profile
spring:
    profiles: production
    application:
        name: Battleships
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:battleship
            username: root
            password: ""
server:
    servlet:
        context-path: /battleship
logging:
    file: log/battleship.log
