spring:
    profiles: development, default
    application:
        name: Battleships

    devtools:
        restart:
            additional-paths: src
            exclude: "**/*.log"
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp
    datasource:
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:battleship
            username: root
            password: ""
    h2:
      console:
        enabled: true
        path: /h2
        settings:
            web-allow-others: true

logging: 
    file: log/battleship.log
